# Generated by Django 5.2 on 2025-05-11 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 18, 55, 5, 777161, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
