# Generated by Django 5.2 on 2025-05-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("djauth", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Groups",
            new_name="Group",
        ),
    ]
