# Generated by Django 5.2 on 2025-05-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0002_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 18, 58, 19, 123295, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
