# Generated by Django 5.2 on 2025-05-14 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0003_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 17, 11, 28, 30, 500831, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
