# Generated by Django 5.2 on 2025-05-14 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0004_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 17, 21, 48, 27, 703244, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
