# Generated by Django 5.2 on 2025-05-15 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0005_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 18, 10, 37, 31, 440403, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
