# Generated by Django 5.2 on 2025-05-17 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0006_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 20, 13, 19, 45, 587146, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
