# Generated by Django 5.2 on 2025-05-17 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djauth", "0008_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 20, 20, 22, 28, 305071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
