# Generated by Django 5.2 on 2025-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, to="post.postimage"),
        ),
    ]
