# Generated by Django 5.2 on 2025-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="file",
            field=models.ImageField(upload_to="media/posts/images/"),
        ),
    ]
