# Generated by Django 5.2 on 2025-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_postimage_file_postcomment_postreaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedpost",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
