# Generated by Django 5.2 on 2025-05-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_sharedpost_caption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcomment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="original_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="post.post",
            ),
        ),
        migrations.DeleteModel(
            name="SharedPost",
        ),
    ]
