# Generated by Django 5.2 on 2025-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_post_is_shared_alter_post_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="saved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="shared",
            field=models.IntegerField(default=0),
        ),
    ]
